# Generated by Django 4.1 on 2022-10-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.CharField(max_length=10)),
                ('cantidadPersonas', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('observacion', models.CharField(max_length=50)),
            ],
        ),
    ]
